[theme]
# Primary accent color for interactive elements.
primaryColor = "#a13228"

# Background color for the main content area.
backgroundColor = "#002b36"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#736665"

# Color used for almost all text.
textColor = "#fff"